# Series & DataFrames

In [38]:
import pandas as pd

In [39]:
df=pd.read_csv('heart-disease.csv')
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [40]:
!ls

'ls' is not recognized as an internal or external command,
operable program or batch file.

In [41]:
series=pd.Series(["BMW","Audi","Mercedes-Benz","Ferrari"])
print(series)

#Series is 1-D 

colors=pd.Series(["Red","blue","yellow","Green"])
print(colors)

0              BMW
1             Audi
2    Mercedes-Benz
3          Ferrari
dtype: object
0       Red
1      blue
2    yellow
3     Green
dtype: object

In [42]:
#Dataframes 2-Dimentional

car_data=pd.DataFrame({"Car Make ":series,"Color":colors})
car_data

       Car Make    Color
0            BMW     Red
1           Audi    blue
2  Mercedes-Benz  yellow
3        Ferrari   Green

In [43]:
#Import data
car_sales=pd.read_csv('car-sales.csv')
car_sales.head()

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00

In [44]:
# axis=1 means column
# axis=0 means row
# index number starts 0 by default

In [45]:
# Exporting a dataframe
car_sales.to_csv('exported-car-sales.csv',index=False) # index=false means to remove added index 
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

## Describe Data

In [48]:
#Attribute
car_sales.dtypes

# Funtion
# car_sales.to_csv()

',Make,Colour,Odometer (KM),Doors,Price\r\n0,Toyota,White,150043,4,"$4,000.00"\r\n1,Honda,Red,87899,4,"$5,000.00"\r\n2,Toyota,Blue,32549,3,"$7,000.00"\r\n3,BMW,Black,11179,5,"$22,000.00"\r\n4,Nissan,White,213095,4,"$3,500.00"\r\n5,Toyota,Green,99213,4,"$4,500.00"\r\n6,Honda,Blue,45698,4,"$7,500.00"\r\n7,Honda,Blue,54738,4,"$7,000.00"\r\n8,Toyota,White,60000,4,"$6,250.00"\r\n9,Nissan,White,31600,4,"$9,700.00"\r\n'

In [50]:
car_sales.columns

Index(['Make', 'Colour', 'Odometer (KM)', 'Doors', 'Price'], dtype='object')

In [53]:
car_columns=car_sales.columns
car_columns

Index(['Make', 'Colour', 'Odometer (KM)', 'Doors', 'Price'], dtype='object')

In [54]:
car_sales.index

RangeIndex(start=0, stop=10, step=1)

In [56]:
car_sales.describe()

       Odometer (KM)      Doors
count      10.000000  10.000000
mean    78601.400000   4.000000
std     61983.471735   0.471405
min     11179.000000   3.000000
25%     35836.250000   4.000000
50%     57369.000000   4.000000
75%     96384.500000   4.000000
max    213095.000000   5.000000

In [57]:
car_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Make           10 non-null     object
 1   Colour         10 non-null     object
 2   Odometer (KM)  10 non-null     int64
 3   Doors          10 non-null     int64
 4   Price          10 non-null     object
dtypes: int64(2), object(3)
memory usage: 532.0+ bytes

In [67]:
car_sales.mean()

TypeError: Could not convert ['ToyotaHondaToyotaBMWNissanToyotaHondaHondaToyotaNissan'
 'WhiteRedBlueBlackWhiteGreenBlueBlueWhiteWhite'
 '$4,000.00$5,000.00$7,000.00$22,000.00$3,500.00$4,500.00$7,500.00$7,000.00$6,250.00$9,700.00'] to numeric

In [70]:
car_prices=pd.Series([30011,72031,12234])
car_prices.mean()

np.float64(38092.0)

In [75]:
car_sales.sum()
car_sales["Doors"].sum()

np.int64(40)

## Viewing And Selecting Data

In [76]:
car_sales.head()
# gives top 4 rows

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00

In [78]:
car_sales.head(7)

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00

In [79]:
car_sales.tail()

     Make Colour  Odometer (KM)  Doors      Price
5  Toyota  Green          99213      4  $4,500.00
6   Honda   Blue          45698      4  $7,500.00
7   Honda   Blue          54738      4  $7,000.00
8  Toyota  White          60000      4  $6,250.00
9  Nissan  White          31600      4  $9,700.00

In [ ]:
# Difference between .loc and .iloc 

animals=pd.Series(["car","dog","bird","panda","snake"],index=[0,3,5,4,3])

# loc refers to index

In [82]:
animals.loc[3]

3      dog
3    snake
dtype: object

In [86]:
car_sales.loc[3]

Make                    BMW
Colour                Black
Odometer (KM)         11179
Doors                     5
Price            $22,000.00
Name: 3, dtype: object

In [90]:
# iloc refers to position 

animals.iloc[3] # Integer-location based index
animals.loc[3] # Label (index value) based index

3      dog
3    snake
dtype: object

In [92]:
animals.iloc[:3]

0     car
3     dog
5    bird
dtype: object

In [94]:
car_sales.loc[:3]
car_sales.iloc[:3]

     Make Colour  Odometer (KM)  Doors      Price
0  Toyota  White         150043      4  $4,000.00
1   Honda    Red          87899      4  $5,000.00
2  Toyota   Blue          32549      3  $7,000.00

In [95]:
car_sales.Make

0    Toyota
1     Honda
2    Toyota
3       BMW
4    Nissan
5    Toyota
6     Honda
7     Honda
8    Toyota
9    Nissan
Name: Make, dtype: object

In [96]:
# car_sales.Odometer (KM)
# it will thorw error as there is a whitespace
# This is the corrected format  
car_sales["Odometer (KM)"]

0    150043
1     87899
2     32549
3     11179
4    213095
5     99213
6     45698
7     54738
8     60000
9     31600
Name: Odometer (KM), dtype: int64

In [98]:
car_sales[car_sales["Make"]=="Toyota"]

     Make Colour  Odometer (KM)  Doors      Price
0  Toyota  White         150043      4  $4,000.00
2  Toyota   Blue          32549      3  $7,000.00
5  Toyota  Green          99213      4  $4,500.00
8  Toyota  White          60000      4  $6,250.00

In [100]:
car_sales[car_sales["Odometer (KM)"]>100000] #Adding Filter

     Make Colour  Odometer (KM)  Doors      Price
0  Toyota  White         150043      4  $4,000.00
4  Nissan  White         213095      4  $3,500.00

In [101]:
pd.crosstab(car_sales['Make'],car_sales["Doors"])

Doors   3  4  5
Make
BMW     0  0  1
Honda   0  3  0
Nissan  0  2  0
Toyota  1  3  0

In [ ]:
car_sales.groupby(['Make']).mean()

TypeError: unhashable type: 'list'